<?php

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function recipes_theme($existing, $type, $theme, $path) {
  return [
    'recipe_preview' => [
      'variables' => [
        'recipe' => NULL,
      ],
      'template' => 'recipe-preview',
    ],
    'add_to_list_button' => [
      'variables' => [
        'label' => NULL,
        'id' => NULL,
        'attributes' => [],
      ],
      'template' => 'form/add-to-list-button',
    ],
    'remove_from_list_button' => [
      'variables' => [
        'label' => NULL,
        'id' => NULL,
        'attributes' => [],
      ],
      'template' => 'form/remove-from-list-button',
    ],
    'recipes_recipe_list' => ['render element' => 'elements'],
  ];
}
