recipes.settings:
  type: config_object
  label: 'Recipes Settings'
  mapping:
    prompt:
      type: text
      label: 'Prompt text'
    use_structured_json_ai_response:
      type: boolean
      label: 'Use structured JSON AI response'